# -*- coding: utf-8 -*-
"""Restaurant Billing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14va_IIPuTJRauXb3rPbWDl9jJHyT6rxV
"""

# Step 1: Create menu and prices using [] and {}
menu = ['pongal', 'dosa', 'tea', 'coffee']
prices = {'pongal': 30, 'dosa': 25, 'tea': 10, 'coffee': 15}

# Step 2: Ask user to enter an item
order = input("Menu: " + str(menu) + "\nEnter your order: ").lower()

# Step 3: Check if item is in menu using ()
if order in menu:
    price = prices[order]
    print(f"{order} is available. Price is ₹{price}")
else:
    print(f"Sorry, {order} is not available.")

# Step 1: Menu and prices
menu = ['pongal', 'dosa', 'tea', 'coffee']
prices = {'pongal': 30, 'dosa': 25, 'tea': 10, 'coffee': 15}

# Step 2: Get order from user
order = input("Menu: " + str(menu) + "\nEnter your order: ").lower()

# Step 3: Check if available
if order in menu:
    quantity = int(input(f"How many {order}s do you want? "))
    price = prices[order]
    total = price * quantity
    print(f"You ordered {quantity} {order}(s). Price per item: ₹{price}. Total bill: ₹{total}")
else:
    print(f"Sorry, {order} is not available.")

# Step 1: Menu and prices
menu = ['pongal', 'dosa', 'tea', 'coffee']
prices = {'pongal': 30, 'dosa': 25, 'tea': 10, 'coffee': 15}

# Step 2: Store the order in a dictionary
order_summary = {}

# Step 3: Show menu
print("🍽️ Menu:")
for item in menu:
    print(f"- {item.title()} : ₹{prices[item]}")

# Step 4: Ordering loop
while True:
    order = input("\nEnter your item (or type 'done' to finish): ").lower()

    if order == 'done':
        break

    if order in menu:
        quantity = int(input(f"How many {order}s do you want? "))
        if order in order_summary:
            order_summary[order] += quantity
        else:
            order_summary[order] = quantity
    else:
        print("❌ Item not in menu. Please choose from the listed items.")

# Step 5: Final Bill
print("\n🧾 Final Bill:")
total = 0
for item, qty in order_summary.items():
    item_total = prices[item] * qty
    total += item_total
    print(f"{item.title()} x {qty} = ₹{item_total}")

print(f"\n💰 Total Amount to Pay: ₹{total}")

# Step 1: Menu and Prices
menu = ['pongal', 'dosa', 'tea', 'coffee']
prices = {'pongal': 30, 'dosa': 25, 'tea': 10, 'coffee': 15}

# Step 2: Order Collection
order_summary = {}

# Step 3: Show Menu
print("🍽️ Menu:")
for item in menu:
    print(f"- {item.title()} : ₹{prices[item]}")

# Step 4: Input Loop
while True:
    order = input("\nEnter your item (or type 'done' to finish): ").lower()
    if order == 'done':
        break

    if order in menu:
        quantity = int(input(f"How many {order}s? "))
        if order in order_summary:
            order_summary[order] += quantity
        else:
            order_summary[order] = quantity
    else:
        print("❌ Not in menu. Try again.")

# Step 5: Bill Calculation
print("\n🧾 Final Bill:")
subtotal = 0
for item, qty in order_summary.items():
    item_total = prices[item] * qty
    subtotal += item_total
    print(f"{item.title()} x {qty} = ₹{item_total}")

# Step 6: GST, Delivery & Discounts
gst = round(subtotal * 0.05)       # 5% GST
delivery_charge = 20
discount = 0

if subtotal > 200:
    discount = round(subtotal * 0.10)  # 10% off

total_amount = subtotal + gst + delivery_charge - discount

# Step 7: Print Full Summary
print(f"\nSubtotal        : ₹{subtotal}")
print(f"GST (5%)        : ₹{gst}")
print(f"Delivery Charge : ₹{delivery_charge}")
print(f"Discount        : ₹{discount}")
print(f"-----------------------------")
print(f"💰 Total to Pay : ₹{total_amount}")